(function bootstrapInstitutionAliases(root, factory) {
  const aliases = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = aliases;
  }
  root.__INSTITUTION_ALIASES__ = aliases;
})(typeof globalThis !== "undefined" ? globalThis : this, () => [
  ["CISPA Helmholtz Center", "CISPA Helmholtz Center for Information Security"],
  ["Chinese Academy of Sciences (CAS)", "Chinese Academy of Sciences"],
  ["德国CISPA亥姆霍兹信息安全中心", "CISPA Helmholtz Center for Information Security"],
  ["德国马克斯普朗克数学研究所（MPIM）; 德国汉诺威莱布尼兹大学", "Max Planck Institute for Mathematics; Leibniz University Hannover"],
  ["Delft University of Technology", "TU Delft"],
  ["Ecole Polytechnique", "École Polytechnique"],
  ["École Polytechnique, France", "École Polytechnique"],
  ["&Eacute;cole Polytechnique", "École Polytechnique"],
  ["Ecole Polytechnique Fédérale de Lausanne (EPFL)", "École Polytechnique Fédérale de Lausanne (EPFL)"],
  ["École polytechnique fédérale de Lausanne", "École Polytechnique Fédérale de Lausanne (EPFL)"],
  ["École Polytechnique Fédérale de Lausanne", "École Polytechnique Fédérale de Lausanne (EPFL)"],
  ["&Eacute;cole Polytechnique F&eacute;d&eacute;rale de Lausanne (EPFL)", "École Polytechnique Fédérale de Lausanne (EPFL)"],
  ["&Eacute; cole Polytechnique", "École Polytechnique"],
  ["&Eacute; cole Polytechnique F&eacute; d&eacute; rale de Lausanne (EPFL)", "École Polytechnique Fédérale de Lausanne (EPFL)"],
  ["É cole Polytechnique", "École Polytechnique"],
  ["É cole Polytechnique Fédé rale de Lausanne (EPFL)", "École Polytechnique Fédérale de Lausanne (EPFL)"],
  ["&Eacute;cole Normale Sup&eacute;rieure", "École Normale Supérieure"],
  ["École Normale Supérieure Paris", "École Normale Supérieure"],
  ["&Eacute;cole Normale Sup&eacute;rieure Paris", "École Normale Supérieure"],
  ["&Eacute;cole Normale Sup&eacute;rieure de Cachan", "École Normale Supérieure de Cachan"],
  ["&Eacute;cole Normale Sup&eacute;rieure de Lyon", "École Normale Supérieure de Lyon"],
  ["&Eacute; cole Normale Sup&eacute; rieure", "École Normale Supérieure"],
  ["&Eacute; cole Normale Sup&eacute; rieure Paris", "École Normale Supérieure"],
  ["&Eacute; cole Normale Sup&eacute; rieure de Cachan", "École Normale Supérieure de Cachan"],
  ["&Eacute; cole Normale Sup&eacute; rieure de Lyon", "École Normale Supérieure de Lyon"],
  ["É cole Normale Supé rieure", "École Normale Supérieure"],
  ["É cole Normale Supé rieure Paris", "École Normale Supérieure"],
  ["É cole Normale Supé rieure de Cachan", "École Normale Supérieure de Cachan"],
  ["É cole Normale Supé rieure de Lyon", "École Normale Supérieure de Lyon"],
  ["电子科技大学", "UESTC"],
  ["法国巴黎萨克雷大学", "Paris-Saclay University"],
  ["复旦大学", "Fudan University"],
  ["海南大学", "Hainan University"],
  ["Hong Kong Polytechnic University", "The Hong Kong Polytechnic University"],
  ["Hong Kong University of Science and Technology", "HKUST"],
  ["The Hong Kong University of Science and Technology", "HKUST"],
  ["荷兰Radboud大学", "Radboud University"],
  ["华中科技大学", "Huazhong University of Science and Technology"],
  ["Indian Institute of Technology (IIT), Bombay", "Indian Institute of Technology Bombay"],
  ["暨南大学", "Jinan University"],
  ["Massachusetts Inst. of Technology", "Massachusetts Institute of Technology"],
  ["美国纽约大学石溪分校; 美国东北大学", "Stony Brook University; Northeastern University"],
  ["美国普渡大学", "Purdue University"],
  ["美国佐治亚理工学院", "Georgia Institute of Technology"],
  ["美国佐治亚理工学院，电子与计算机工程学院", "Georgia Institute of Technology"],
  ["美国佐治亚理工学院; 佐治亚州立大学", "Georgia Institute of Technology; Georgia State University"],
  ["佐治亚州立大学", "Georgia State University"],
  ["南京大学", "Nanjing University"],
  ["南京邮电大学", "Nanjing University of Posts and Telecommunications"],
  ["山东大学", "Shandong University"],
  ["上海交通大学", "Shanghai Jiao Tong University"],
  ["Southern University of Science and Technology", "SUSTech"],
  ["天津大学", "Tianjin University"],
  ["Univ. of California - Berkeley", "University of California, Berkeley"],
  ["Univ. of Illinois at Urbana-Champaign", "University of Illinois Urbana-Champaign"],
  ["武汉大学", "Wuhan University"],
  ["香港科技大学", "HKUST"],
  ["香港理工大学", "The Hong Kong Polytechnic University"],
  ["The Hong Kong Polytechnic Univ.", "The Hong Kong Polytechnic University"],
  ["Zhejiang University, China", "Zhejiang University"],
  ["中国人民大学", "Renmin University of China"],
  ["中国科学技术大学", "University of Science and Technology of China"],
  ["中国科学院研究生院", "University of Chinese Academy of Sciences"],
  ["中国科学院信息工程研究所", "Institute of Information Engineering, Chinese Academy of Sciences"],
  ["中国科学院计算技术研究所", "Institute of Computing Technology, Chinese Academy of Sciences"],
  ["中国科学院软件研究所", "Institute of Software, Chinese Academy of Sciences"],
  ["北京大学", "Peking University"],
  ["北京邮电大学", "Beijing University of Posts and Telecommunications"],
  ["浙江大学", "Zhejiang University"],
  ["华中理工大学", "Huazhong University of Science and Technology"],
  ["厦门大学", "Xiamen University"],
  ["新加坡国立大学", "National University of Singapore"],
  ["新加坡南洋理工大学", "Nanyang Technological University"],
  ["新加坡科技设计大学", "Singapore University of Technology and Design"],
  ["清华大学", "Tsinghua University"],
  ["美国伍斯特理工学院", "Worcester Polytechnic Institute"],
  ["美国北卡罗莱纳州立大学", "North Carolina State University"],
  ["美国罗格斯 (Rutgers, The State University of New Jersey）", "Rutgers University"],
  ["赫尔辛基工业大学", "Aalto University"],
  ["香港中文大学", "The Chinese University of Hong Kong"],
]);
